/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.2.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the java-library plugin for API and implementation separation.
    `java-library`
    `maven-publish`
    id("com.github.monosoul.yadegrap") version "1.0.0"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit test framework.
    testImplementation("junit:junit:4.13.2")

    // This dependency is exported to consumers, that is to say found on their compile classpath.
    api("org.apache.commons:commons-lang3:3.12.0")
    api("org.apache.commons:commons-text:1.10.0")
    api("com.squareup.okhttp3:okhttp:4.10.0")
    api("com.google.code.gson:gson:2.10.1")
    implementation("org.slf4j:slf4j-api:2.0.7")

    // This dependency is used internally, and not exposed to consumers on their own compile classpath.
    compileOnly("org.projectlombok:lombok:1.18.28")
    annotationProcessor("org.projectlombok:lombok:1.18.28")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(8))
    }
}

configure<PublishingExtension> {
    publications {
        publications.create<MavenPublication>("mavenJava") {
            from(components["java"])
            repositories {
                maven {
                    name = "GitHubPackages"
                    artifactId = "googlebardclient"
                    url = uri("https://maven.pkg.github.com/ndanhkhoi/GoogleBardClient")
                    credentials {
                        username = System.getenv("GITHUB_ACTOR")
                        password = System.getenv("GITHUB_TOKEN")
                    }
                }
            }
        }
    }
}

tasks {
    test {
        useJUnitPlatform()
    }

    jar {
        archiveBaseName.set("simple-telegram-command-bot-spring-boot-starter")
    }

    val delombok = "delombok"(com.github.monosoul.yadegrap.DelombokTask::class)

    javadoc {
        dependsOn(delombok)
        setSource(delombok)
        isFailOnError = false
        title = "Google Bard Client"
        options.encoding = "UTF-8"
    }
}